# Generated by Django 4.2.11 on 2025-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_bkashconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('app_key', models.CharField(max_length=100)),
                ('app_secret', models.CharField(max_length=100)),
                ('sandbox', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
