# Generated by Django 4.2.11 on 2025-02-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_bkashconfiguration_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
