# Generated by Django 4.2.11 on 2025-02-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
