# Generated by Django 4.2.11 on 2025-03-12 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_purchase_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
