# Generated by Django 4.2.11 on 2025-03-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0014_remove_gallery_image_gallery_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='amount_paid',
            new_name='amount',
        ),
    ]
