# Generated by Django 4.2.11 on 2025-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0015_rename_amount_paid_purchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('PURCHASE', 'Purchase')], default='Purchase', max_length=10),
        ),
    ]
