# Generated by Django 4.2.11 on 2025-03-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0016_alter_purchase_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('PARTIAL', 'Partial'), ('PURCHASE', 'Purchase')], default='Pending', max_length=10),
        ),
    ]
