# Generated by Django 4.2.11 on 2025-04-13 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0013_courses_slug'),
        ('landingpage', '0017_alter_purchase_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsfeatures.courses'),
        ),
    ]
