# Generated by Django 4.2.11 on 2025-04-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_banneritem_mobile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banneritem',
            name='button',
            field=models.ManyToManyField(blank=True, null=True, to='cms.button'),
        ),
        migrations.AlterField(
            model_name='banneritem',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
