# Generated by Django 4.2.11 on 2025-11-11 10:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0013_courses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='extra_description',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
