# Generated by Django 4.2.11 on 2025-11-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0014_courses_extra_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_content_type',
            field=models.CharField(choices=[('test_exam', 'Test Exam'), ('live_course', 'Live Course'), ('recourse', 'Recourse'), ('full_courses', 'Full Courses')], default='full_courses', max_length=15),
        ),
    ]
