# Generated by Django 4.2.11 on 2025-11-11 20:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('globalapp', '0014_basebeneficariesmodel'),
        ('lmsfeatures', '0015_courses_course_content_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('common_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='globalapp.common')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('right_answer', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], help_text='Select the correct option letter (A/B/C/D)', max_length=1)),
            ],
            bases=('globalapp.common',),
        ),
        migrations.RemoveField(
            model_name='coursecontents',
            name='preview',
        ),
        migrations.AddField(
            model_name='coursecontents',
            name='examtime',
            field=models.IntegerField(blank=True, help_text='Minutes (only required for quiz contents)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='coursecontents',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('resources', 'Resources')], default='video', max_length=10),
        ),
        migrations.AlterField(
            model_name='coursecontents',
            name='installment_status',
            field=models.ManyToManyField(blank=True, to='lmsfeatures.installationstatus'),
        ),
        migrations.AlterField(
            model_name='coursecontents',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursecontents',
            name='mcq',
            field=models.ManyToManyField(blank=True, related_name='course_contents', to='lmsfeatures.mcqquestion'),
        ),
    ]
