# Generated by Django 4.2.11 on 2025-11-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsfeatures', '0016_mcqquestion_remove_coursecontents_preview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontents',
            name='preview',
            field=models.BooleanField(default=False),
        ),
    ]
